import re
import types
import cgi


NON_CHARS = r''

# Match most urls
URL_REGEX1 = r'(http|www\.)[^\s<>\(\)\[\],]+[\.]+[^\s<>\(\)\[\],.]+' % { 'nc': NON_CHARS }

# Match short urls without www or http for [com|org|net]
# URL_REGEX2 = r'[^\s<>;&]+[\.]+(com|org|net)[^\s<>;&]+'

# Match email addresses
EMAIL_REGEX = r'[^\s<>\(\)\[\],<>]+@[^\s<>\(\)\[\],<>]+\.+[^\s<>\(\)\[\],.<>]+' % { 'nc': NON_CHARS }

# Match US Phone Numbers
PHONE_REGEX = r'([1][\.\- ])?[0-9]{3}[\.\- ][0-9]{3}[\.\- ][0-9]{4}'


def email_handler(match):
    text = match.group(0)
    if text.startswith("<"):
        text = text[1:]
        start = "<"
    if text.endswith(">"):
        text = text[:-1]
        tail = ">"
    if text.startswith("&lt;"):
        text = text[4:]
        start = "&lt;"
    if text.endswith("&gt;"):
        text = text[:-4]        
        tail = "&gt;"

    return '%(start)s<a href="mailto:%(email)s" target="_blank">%(email)s</a>%(tail)s' % \
    { 'email': text, 'tail': tail, 'start': start}

def url_handler(match):
    text = match.group(0)
    start = ""
    tail = ""
    if text.startswith("<"):
        text = text[1:]
        start = "<"
    if text.endswith(">"):
        text = text[:-1]
        tail = ">"
    if text.startswith("&lt;"):
        text = text[4:]
        start = "&lt;"
    if text.endswith("&gt;"):
        text = text[:-4]        
        tail = "&gt;"
    url = text
    if not url.startswith("http"):
        url = "http://" + url
    return '%(start)s<a href="%(url)s" target="_blank">%(text)s</a>%(tail)s' % \
        { 'url': url, 'text': text, 'start': start, 'tail': tail }

def phone_handler(match):
    text = match.group(0)
    onlynum = ''.join(c for c in text if c.isdigit())
    return '<a href="tel:%(num)s" target="_blank">%(num)s</a>' % { 'num': onlynum }

def linky_plain(text, **kwargs):
    text = cgi.escape(text)
    print kwargs
    return linky(text, **kwargs)

def linky(text, url_regex=URL_REGEX1, email_regex=EMAIL_REGEX, \
    phone_regex=PHONE_REGEX, url_callback=url_handler, email_callback=email_handler, \
    phone_callback=phone_handler):
    print email_callback
    newtext = text

    if email_callback:
        newtext = re.sub(email_regex, email_callback, newtext, flags=re.I)

    if phone_callback:
        newtext = re.sub(phone_regex, phone_callback, newtext, flags=re.I)

    if url_callback:
        if isinstance(url_regex, types.StringTypes):
            newtext = re.sub(url_regex, url_callback, newtext, flags=re.I)
        else:
            for regex in url_regex:
                newtext = re.sub(regex, url_callback, newtext, flags=re.I)

    return newtext

card = """
Steven Lee Osborn <osborn.steven@gmail.com>
phone: 918.513.1392
blog: <http://steven.bitsetters.com>
twitter: www.twitter.com/steve918
foo.com
@steve918
"""

email_test = """
--- FastMail Support Ticket ---
This is an automated email generated by the FastMail support
ticket system for support ticket 494378.

DO NOT REPLY TO THIS EMAIL. REPLIES WILL NOT BE MONITORED.

To view the status of this ticket at any time, or to add an update, please use the link below in your web browser.

Ticket Link: <https://www.fastmail.fm/html/?MSignal=TZ-**494378*d5a48f65>

--- Ticket Update  (by Yassar Ali) (date 2014-07-31 18:02:22 UTC) (id 1441594) ---
Hi,

The username of your account is actually:

 stevenosborn@fastmail.net

You can use the above username to login to your account.

If you have lost your password, please update this ticket with details of evidence that you are the owner of the account. As many details as possible from the following list will help with this:

1) Your full account username
2) The "Full Name" thats specified on the account
3) For paid accounts, the last 4 digits of the card used to pay for the account and the card expiry date
4) A few names in your address book.
5) Subjects of the most recent mails you read and sent
6) Your SignUp Date and Last Login Date.
7) Some of the folders in your login.
8) Your backup email address as in the account.
9) IP address(es) from which you have been accessing your account. 
   If you are not sure of the IP, please mention the most recent ISP(s) through which you have been accessing this account.
   To find your IP, just go to http://www.ipchicken.com

Note that, for security reasons, if you can't provide enough details or if most of the details you give us do not match with your account, I am afraid, we will not be able to give you access to the account.

So, please make sure you include as many details as possible. These details help us determine the authenticity of the password request and we'll get back to you with further instructions on resetting your password.

Regards.

--- End Update ---

--- Ticket Update  (by osborn.steven@gmail.com) (date 2014-07-30 18:25:59 UTC) (id 1439850) ---
I believe my account name is stevenosborn@fastmail.fm but the support form doesn't want to accept it so that might be part of my problem.

I recently created an account to evaluate fastmail and I am forwarding email from my personal account, osborn.steven@gmail.com and my work account steven@urbanairship.com, but I somehow managed to save the wrong password in my password manager and I am no longer able to access my account.
Your email is osborn.steven@gmail.com.
Your email is not osborn.steven@foo.bar.gmail.com.
goto: http://foobar.com.
not: https://www.foo.bar.fee.com?asdf=123&asdidf#inbox
[https://www.foo.bar.fee.com?asdf=123&asdidf#inbox]
{https://www.foo.bar.fee.com?asdf=123&asdidf#inbox}
(https://www.foo.bar.fee.com?asdf=123&asdidf#inbox)
<a href="http://google.com"></a>
--- End Update ---
"""
print "<pre>" + linky_plain(card, email_callback=None) + "</pre>"
# print "<pre>" + linky_plain(email_test) + "</pre>"
